# Generated by Django 3.0.4 on 2020-04-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('datePosted', models.DateTimeField(auto_now_add=True)),
                ('dateTaken', models.DateField()),
                ('picture', models.FilePathField(path='/static/pictures')),
            ],
        ),
    ]
