# Generated by Django 3.0.4 on 2020-04-18 04:22

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.FilePathField(path=myapp.models.images_path),
        ),
    ]
