# Generated by Django 3.0.4 on 2020-04-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200418_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default=21, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
